### ISSUE TITLE
示例数据运行报错

### ISSUE THREAD

**Issue by CG050523** [GREAT-WHU/GREAT-PVT#1]
**示例数据在按照指定要求键入命令后无法解算**
![图片](https://github.com/user-attachments/assets/008315b9-dc9b-41f0-b13c-f299c35cacf2)
GLONASS的频段似乎都无法使用
想请教一下是我的编译过程出问题了，还是说xml文件配置有问题
使用的解算数据文件是源码内提供的**PPPFLT_2023305**的文件
我键入的解算命令如下：
**/home/lai/文档/PPP/GREAT-PVT/src/build_Linux/Bin/GREAT_PVT -x xml/GREAT_PPPFLT.xml > result/PPP.log**

**Comment by Jas0nG** [comment]
我遇到了相同的问题，经过排查应该是解析 rinexo 文件时，文件路径存在转义字符 '\\' 导致的。  
## 问题原因
在如下的解析代码中：
https://github.com/GREAT-WHU/GREAT-PVT/blob/main/src/LibGnut/gcoders/rinexo2.cpp#L174-L203  
``` c++
            size_t n = count(filename.begin(), filename.end(), '_');
            if (!_fname.empty())
            {
                if (_fname.length() > 8 + 4 && n >= 5)
                {
                    guess = filename.substr(0, 9);
                    src = "FILE";
                    typ = "long";
                    sit = "(9-CH)";
                } // LONG  FILE NAME
                else
                {
                    guess = filename.substr(0, 4);
                    src = "FILE";
                    typ = "short";
                    sit = "(4-CH)";
                } // SHORT FILE NAME
                transform(guess.begin(), guess.end(), guess.begin(), ::toupper);

                if (guess != marker)
                {

                    if (_spdlog)
                        SPDLOG_LOGGER_DEBUG(_spdlog, src + ": " + typ + " site name: " + guess + " " + sit);
                    if (guess.substr(0, 4) != marker.substr(0, 4))
                    {
                        mesg(GWARNING, "Warning: 4-CHAR: MARKER_NAME [" + marker + "] not equal to site from filename [" + guess + "]");
                    }
                }
            }
            
```

由于转义符存在，guess变量将会被异常截断，而不是正常的 “ALIC” 或 “HERS”。
## 解决
可以通过修改`GREAT_PPPFLT.xml`中的路径解决这个问题：
```xml
        <rinexo>                                                        <!--> rinex obs file <!--> 
            obs/alic3050.23o
            obs/hers3050.23o
        </rinexo>
```

Hope this helps ~

**Comment by CG050523** [comment]
**问题已解决**
原来是路径分隔符的问题，没注意到这个小问题，非常感谢
:100:
: -)

**Comment by ylx1129** [comment]
请注意Windows下使用“\”，Linux下使用"/"。

**Comment by Yqqqqy** [comment]
请教一下如何使用great-pvt跑pppar实验呢？我在xml文件中没有看到相关的配置说明

**Comment by CG050523** [comment]
> 请教一下如何使用great-pvt跑pppar实验呢？我在xml文件中没有看到相关的配置说明

模糊度固定的选项不是在xml文件的最后部分吗，是否搜索，还有宽窄巷固定
---
``` xml
<ambiguity>
        <fix_mode>          SEARCH      </fix_mode>                                 <!--> ambiguity fixed mode (NO/SEARCH) <!-->
        <upd_mode>          UPD         </upd_mode>                                 <!--> upd mode <!-->                                              
        <part_fix>          YES         </part_fix>                                 <!--> part_fix (YES/NO) <!-->  
        <part_fix_num>      4           </part_fix_num>                             <!--> threshold in partial ambiguity fixing <!-->
        <ratio>             2.0         </ratio>                                    <!--> threshold in LAMBDA method <!-->       
        <set_refsat>        YES         </set_refsat>                               <!--> set_refsat (YES/NO) <!-->
        <min_common_time>   1           </min_common_time>                          <!--> minimum common time/seconds <!-->                     
        <extra_widelane_decision maxdev = "0.07" maxsig = "0.10" alpha = "1000" />  <!--> extra widelane setting, alpha&maxdev(Confidence interval parameter), maxsig(maximum sigma) <!-->
        <widelane_decision maxdev = "0.25" maxsig = "0.12" alpha = "1000" />        <!--> widelane setting, option: alpha&maxdev(Confidence interval parameter), maxsig(maximum sigma) <!-->
        <narrowlane_decision maxdev = "0.35" maxsig = "0.12" alpha = "1000" />      <!--> narrowlane setting, option: alpha&maxdev(Confidence interval parameter), maxsig(maximum sigma) <!-->
    </ambiguity>
```

**Comment by Yqqqqy** [comment]
明白了 感谢感谢










 杨秋垣
***@***.***











Original:
***@***.***>Date：2025-03-11 15:11:56(中国 (GMT+08:00))To：GREAT-WHU/GREAT-PVT ***@***.***>Cc：BushiGemeng ***@***.***> , Comment ***@***.***>Subject：Re: [GREAT-WHU/GREAT-PVT] 示例数据运行报错 (Issue #1)请教一下如何使用great-pvt跑pppar实验呢？我在xml文件中没有看到相关的配置说明
模糊度固定的选项不是在xml文件的最后部分吗，是否搜索，还有宽窄巷固定<ambiguity>
        <fix_mode>          SEARCH      </fix_mode>                                 
        <upd_mode>          UPD         </upd_mode>                                                                               
        <part_fix>          YES         </part_fix>                                   
        <part_fix_num>      4           </part_fix_num>                             
        <ratio>             2.0         </ratio>                                           
        <set_refsat>        YES         </set_refsat>                               
        <min_common_time>   1           </min_common_time>                                               
        <extra_widelane_decision maxdev = "0.07" maxsig = "0.10" alpha = "1000" />  
        <widelane_decision maxdev = "0.25" maxsig = "0.12" alpha = "1000" />        
        <narrowlane_decision maxdev = "0.35" maxsig = "0.12" alpha = "1000" />      
    </ambiguity>
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
CG050523 left a comment (GREAT-WHU/GREAT-PVT#1)
请教一下如何使用great-pvt跑pppar实验呢？我在xml文件中没有看到相关的配置说明
模糊度固定的选项不是在xml文件的最后部分吗，是否搜索，还有宽窄巷固定<ambiguity>
        <fix_mode>          SEARCH      </fix_mode>                                 
        <upd_mode>          UPD         </upd_mode>                                                                               
        <part_fix>          YES         </part_fix>                                   
        <part_fix_num>      4           </part_fix_num>                             
        <ratio>             2.0         </ratio>                                           
        <set_refsat>        YES         </set_refsat>                               
        <min_common_time>   1           </min_common_time>                                               
        <extra_widelane_decision maxdev = "0.07" maxsig = "0.10" alpha = "1000" />  
        <widelane_decision maxdev = "0.25" maxsig = "0.12" alpha = "1000" />        
        <narrowlane_decision maxdev = "0.35" maxsig = "0.12" alpha = "1000" />      
    </ambiguity>
